import Head from 'next/head';

interface HeadProps {
  title?: string;
}

const Meta = ({ title }: HeadProps) => {
  return (
    <Head>
      <title>{title ? title : 'Life: on the brink'}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Lexend&family=Nunito:ital,wght@0,200;0,400;0,700;1,200;1,400;1,700&display=swap" rel="stylesheet" />
    </Head>
  );
};

export default Meta;